abci = "socket"
db_backend = "pebbledb"
db_dir = "data"
filter_peers = false
genesis_file = "config/genesis.json"
log_format = "plain"
log_level = "consensus:info,abci:info,*:info"
moniker = ""
node_key_file = "config/node_key.json"
priv_validator_key_file = "config/priv_validator_key.json"
priv_validator_laddr = ""
priv_validator_state_file = "data/priv_validator_state.json"
proxy_app = "tcp://reth-rpc-node:26658"
version = "1.0.0"

[blocksync]
version = "v0"

[consensus]
create_empty_blocks = true
create_empty_blocks_interval = "0s"
double_sign_check_height = 0
peer_gossip_intraloop_sleep_duration = "0s"
peer_gossip_sleep_duration = "100ms"
peer_query_maj23_sleep_duration = "2s"
skip_timeout_commit = false
timeout_propose = "1s"           # default: 3s
timeout_propose_delta = "100ms"  # default: 500ms
timeout_prevote = "500ms"        # default: 1s  
timeout_prevote_delta = "100ms"  # default: 500ms
timeout_precommit = "500ms"      # default: 1s
timeout_precommit_delta = "100ms" # default: 500ms
timeout_commit = "1s"            # default: 1s (this is the key one for block time)

wal_file = "data/cs.wal/wal"

[grpc]
laddr = ""

[grpc.block_results_service]
enabled = true

[grpc.block_service]
enabled = true

[grpc.privileged]
laddr = ""

[grpc.privileged.pruning_service]
enabled = false

[grpc.version_service]
enabled = true

[instrumentation]
max_open_connections = 3
namespace = "cometbft"
prometheus = false
prometheus_listen_addr = ":26660"

[mempool]
broadcast = true
cache_size = 10000
experimental_max_gossip_connections_to_non_persistent_peers = 0
experimental_max_gossip_connections_to_persistent_peers = 0
keep-invalid-txs-in-cache = false
max_tx_bytes = 1048576
max_txs_bytes = 67108864
recheck = true
recheck_timeout = "1s"
size = 5000
type = "flood"
wal_dir = ""

[p2p]
addr_book_file = "config/addrbook.json"
addr_book_strict = false
allow_duplicate_ip = true
dial_timeout = "3s"
external_address = ""
flush_throttle_timeout = "10ms"
handshake_timeout = "20s"
laddr = "tcp://0.0.0.0:26656"
max_num_inbound_peers = 40
max_num_outbound_peers = 10
max_packet_msg_payload_size = 1024
persistent_peers = "a491a5a7b33fad2d52749c273dbd454d2f85b9b8@barcelona.botanix.io:26656,f390c94c8445b3fdf99da24acfa58a39eabddd1b@chelsea.botanix.io:26656,4d81aaee32ed59fe0e66288786365e02af7c258e@liverpool.botanix.io:26656,e90497f8fb232f192d156f5f85a34b863376eef2@madrid.botanix.io:26656,d8bc85c5ed2b155f08bdbe2d2d61717a5f765fff@arsenal.botanix.io:26656,1482fae7da43fcc82873a71d688c8118eeb29027@manchester.botanix.io:26656"
persistent_peers_max_dial_period = "0s"
pex = true
private_peer_ids = ""
recv_rate = 5120000
seed_mode = false
seeds = ""
send_rate = 5120000
unconditional_peer_ids = ""

[rpc]
cors_allowed_headers = [
    "Origin",
    "Accept",
    "Content-Type",
    "X-Requested-With",
    "X-Server-Time",
]
cors_allowed_methods = [
    "HEAD",
    "GET",
    "POST",
]
cors_allowed_origins = []
experimental_close_on_slow_client = false
experimental_subscription_buffer_size = 200
experimental_websocket_write_buffer_size = 200
laddr = "tcp://0.0.0.0:26657"
max_body_bytes = 1000000
max_header_bytes = 1048576
max_open_connections = 900
max_request_batch_size = 10
max_subscription_clients = 100
max_subscriptions_per_client = 5
pprof_laddr = ""
timeout_broadcast_tx_commit = "10s"
tls_cert_file = ""
tls_key_file = ""
unsafe = false

[statesync]
chunk_fetchers = "4"
chunk_request_timeout = "10s"
discovery_time = "15s"
enable = false
rpc_servers = ""
temp_dir = ""
trust_hash = ""
trust_height = 0
trust_period = "168h0m0s"

[storage]
compact = false
compaction_interval = "1000"
discard_abci_responses = false
experimental_db_key_layout = "v1"

[storage.pruning]
interval = "10s"

[storage.pruning.data_companion]
enabled = false
initial_block_results_retain_height = 0
initial_block_retain_height = 0

[tx_index]
indexer = "kv"
psql-conn = ""